name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, gd, bcmath
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Copy .env.example to .env
        run: cp env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

  deploy:
    name: Deploy to AWS EC2
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://skaldiccodeworks.dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/skaldic-codeworks
            git pull origin main
            bash scripts/deploy.sh

      - name: Health check
        run: |
          sleep 10
          curl -f https://skaldiccodeworks.dev || exit 1

      - name: Notify on success
        if: success()
        run: echo "✓ Deployment completed successfully"

      - name: Notify on failure
        if: failure()
        run: |
          echo "✗ Deployment failed"
          exit 1

